---
driver:
  name: vagrant
  vagrantfile_erb: Vagrantfile.erb

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-5.10
  - name: centos-6.4
  - name: centos-6.5
  - name: centos-6.6
  - name: centos-7.0


suites:
  - name: ovirt-repo
    run_list:
      - recipe[guest-agent::ovirt_repo]
    attributes:
